apiVersion: v1
kind: Secret
metadata:
  name: {{ include "url-shortener.fullname" . }}-secret
  labels:
    {{- include "url-shortener.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "url-shortener.databaseUrl" . | quote }}
